//
//  FirstWorker.swift
//  LeoVip
//
//  Created by tecH on 13/05/20.
//  Copyright (c) 2020 vijayvir Singh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol CandyAPIWorkerProtocol {
    func fetchCandy(callBack:(CandyEntity) -> Void)
}

class FirstWorker : CandyAPIWorkerProtocol
{
      func fetchCandy(callBack:(CandyEntity) -> Void) {
      let candyEntity = CandyEntity(title: "Magic Candy",
                                    description: "Magic candies coming from heaven, if you eat one and say a wish. Your wish will be granted.",
                                    price: 100,
                                    imageName: "magic_candy")
      callBack(candyEntity)
    }
    
}
