//
//  SecondInteractor.swift
//  LeoVip
//
//  Created by tecH on 13/05/20.
//  Copyright (c) 2020 vijayvir Singh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SecondBusinessLogic
{
  func doSomething(request: Second.Something.Request)
}

protocol SecondDataStore
{
  //var name: String { get set }
}

class SecondInteractor: SecondBusinessLogic, SecondDataStore
{
  var presenter: SecondPresentationLogic?
  var worker: SecondWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Second.Something.Request)
  {
    worker = SecondWorker()
    worker?.doSomeWork()
    
    let response = Second.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
