//
//  SecondPresenter.swift
//  LeoVip
//
//  Created by tecH on 13/05/20.
//  Copyright (c) 2020 vijayvir Singh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SecondPresentationLogic
{
  func presentSomething(response: Second.Something.Response)
}

class SecondPresenter: SecondPresentationLogic
{
  weak var viewController: SecondDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Second.Something.Response)
  {
    let viewModel = Second.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
